language: node_js
node_js:
  - "14"

script: npm run build -- --prefix-paths

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository as a secure variable
  github_url: "<ghe-url>" # TODO Set this to your GHE url, e.g. "github.example.com"
  on:
    branch: main
